### ISSUE TITLE
Issue with the parser prob initialization

### ISSUE THREAD

**Issue by BernieMayer** [kahosks/CPSC433#3]
How does this line 154 cause a unique representation for each slot. So that we can tell be between a tuesday 10:00 and a monday 10:00.

The line is:
initialProblem[i] = pClass.getTimeInt();

**Comment by lucmichaud** [comment]
added this
day = pClass.getDay();
if(day.equals("TU")) {
    initialProblem[i] += 2400;
} else if(day.equals("FR")) {
    initialProblem[i] += 4800;
}

Now if the int is less than 2400 it is on Monday
between 2400 and 4800 it is on Tuesday
over 4800 it is on Friday
